config/routes.rb
Rails.application.routes.draw do
  root 'blogs#top'
  resources :blogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :content, presence: true, length: { maximum:140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end

  def show
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = Blog.new(blog_params)
      respond_to do |format|
        if @blog.valid? && params[:confirm]
          format.html { render :new_confirm }
        elsif params[:back]
          format.html { render :new }
        elsif @blog.save
          format.html { redirect_to @blog, notice: 'つぶやきが登録されました' }
          format.json { render :show, status: :created, location: @blog }
        else
          format.html { render :new }
          format.json { render json: @blog.errors, status: :unprocessable_entity }
        end
      end
  end

  def update
    @blog.assign_attributes(blog_params)
    respond_to do |format|
      if @blog.valid? && params[:confirm]
        format.html { render :edit_confirm }
      elsif params[:back]
        format.html { render :edit }
      elsif @blog.save
        format.html { redirect_to @blog, notice: 'つぶやきが更新されました' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'つぶやきが削除されました' }
      format.json { head :no_content }
    end
  end

  private
  def set_blog
    @blog = Blog.find(params[:id])
  end
  def blog_params
      params.require(:blog).permit(:content)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_confirm.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <div class="field">
    <%= form.label :以下の内容でよろしいですか？ %><br>
    <%= blog.content %>
    <%= form.hidden_field :content %><br><br>
  </div>
  <div class="actions">
    <%= form.submit 'やめる', name: 'back' %>
    <%= form.submit 'つぶやく' %>
  </div>
<% end %>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :つぶやき %>
    <%= form.text_area :content, placeholder:"１４０文字以内でつぶやいてね" %>
  </div>

  <div class="actions">
    <%= form.submit 'つぶやく' , name:'confirm' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<body style = "margin:0px">

    <header style ="background-color:teal;height:80px; color:lightsteelblue;top:0px;left:0px; margin-top:-40px;padding-top:20px">
        <p style= "font-size:30px">RITTER</p>
    </header>

    <div style= "height:400px; padding:20px">

        <h1>つぶやき編集</h1>
        <%= render 'form', blog: @blog %>
        <%= link_to '一覧', blogs_path %>

    </div>

    <footer style= "background-color:skyblue; height:30px; font-size:24px; width:100%">
       <p style = "text-align:right">designed by Yasutaka Ikeda</p>
    </footer>

</body>

app/views/blogs/edit_confirm.html.erb
<body style = "margin:0px">
<header style ="background-color:teal;height:80px; color:lightsteelblue;top:0px;left:0px; margin-top:-40px;padding-top:20px">
<p style= "font-size:30px">RITTER</p>
</header>
<div style= "height:400px; padding:20px">

<%= render 'confirm', blog: @blog %>

</div>
<footer style= "background-color:skyblue; height:30px; font-size:24px; width:100%">
<p style = "text-align:right">designed by Yasutaka Ikeda</p>
</footer>
</body>

app/views/blogs/index.html.erb
<body style = "margin:0px">

  <header style ="background-color:teal;height:80px; color:lightsteelblue;top:0px;left:0px; margin-top:-40px;padding-top:20px">
    <p style= "font-size:30px">RITTER</p>
  </header>

  <div style= "height:400px; padding:20px">

    <p id="notice"><%= notice %></p>
    <h1>つぶやき一覧</h1>

    <table>
      <thead>
        <tr>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @blogs.each do |blog| %>
          <tr>
            <td><%= blog.content %></td>
            <td><%= link_to '編集', edit_blog_path(blog) %></td>
            <td><%= link_to '削除', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table><br>

    <%= link_to 'つぶやく', new_blog_path %>

  </div>

  <footer style= "background-color:skyblue; height:30px; font-size:24px; width:100%">
    <p style = "text-align:right">designed by Yasutaka Ikeda</p>
  </footer>
</body>

app/views/blogs/new.html.erb
<body style = "margin:0px">
    <header style ="background-color:teal;height:80px; color:lightsteelblue;top:0px;left:0px; margin-top:-40px;padding-top:20px">
        <p style= "font-size:30px">RITTER</p>
    </header>

    <div style= "height:400px; padding:20px">
        <h1>つぶやき</h1>
        <%= render 'form', blog: @blog %>
        <%= link_to '一覧', blogs_path %>
    </div>

    <footer style= "background-color:skyblue; height:30px; font-size:24px; width:100%">
        <p style = "text-align:right">designed by Yasutaka Ikeda</p>
    </footer>
</body>

app/views/blogs/new_confirm.html.erb
<body style = "margin:0px">
    <header style ="background-color:teal;height:80px; color:lightsteelblue;top:0px;left:0px; margin-top:-40px;padding-top:20px">
        <p style= "font-size:30px">RITTER</p>
    </header>

    <div style= "height:400px; padding:20px">

    <%= render 'confirm', blog: @blog %>

    </div>

    <footer style= "background-color:skyblue; height:30px; font-size:24px; width:100%">
        <p style = "text-align:right">designed by Yasutaka Ikeda</p>
    </footer>
</body>

app/views/blogs/show.html.erb
<body style = "margin:0px">
  <header style ="background-color:teal;height:80px; color:lightsteelblue;top:0px;left:0px; margin-top:-40px;padding-top:20px">
     <p style= "font-size:30px">RITTER</p>
  </header>
  <div style= "height:400px; padding:20px">
    <p id="notice"><%= notice %></p>
    <p>
      <strong>つぶやき:</strong>
      <%= @blog.content %>
    </p>
    <%= link_to '編集', edit_blog_path(@blog) %> 
    <%= link_to '一覧', blogs_path %>
  </div>
  <footer style= "background-color:skyblue; height:30px; font-size:24px; width:100%">
    <p style = "text-align:right">designed by Yasutaka Ikeda</p>
  </footer>
</body>

app/views/blogs/top.html.erb
<body style = "margin:0px">
    <header style ="background-color:teal;height:80px; color:lightsteelblue;top:0px;left:0px; margin-top:-40px;padding-top:20px">
        <p style= "font-size:30px">RITTER</p>
    </header>

    <div style= "height:520px; padding:20px">
        <h1>ruby on rails 課題サイト TOP</h1>
        <%= link_to '一覧へ', blogs_path %>
        <%= link_to 'つぶやく', new_blog_path %>
        <br>
        <P>Ruby on Railsを使ったアプリケーションであること</P>  
        <P>HTML,CSSを使用して、最低限のフロント部分（header,footer,topページ）を作成すること。</P>  
        <P>（JavaScriptは余裕があれば実装する程度で構わない。高度なデザインにしたい場合は次の教材を先に読み、bootstrapなどのCSSフレームワークを使用しても構わない。）</P>  
        <P>tweetの投稿・投稿確認・編集・一覧表示・削除機能があること</P>
        <P>確認画面から投稿画面に戻った時、打ち込んだ内容が保持されるようにすること</P>  
        <P>1文字以上140文字以下しかつぶやけないようにすること</P>
        <P>140文字より多い文字数、または内容が空で登録しようとした場合エラーメッセージが出るようにすること</P>  
        <P>tweetsテーブルは、本文（content）のみカラムを有すること（id,timestampはデフォルトで生成されるのでそのままで良い）</P>  
        <P>Githubにソースコードを送信し、そのリポジトリのURLを提出すること</P>
        <P>エラーが出ないようにすること</P>
        <P>コミットメッセージが、一目見てそのコミットの意味がわかるものであること</P>
        <P>一つの機能を作成したら、一つのコミットをするようにすること（下記ヒントあり）</P>
        <P>タイムゾーンの設定を日本にしておくこと（下記ヒントあり）</P>
        <P>下記に記述してあるコーディング規約に沿った実装を行うこと</P>
        <P>bootstrap, jquery-rails, デバック関係以外のgemを使用していないこと</P>
    </div>

    <footer style= "background-color:skyblue; height:30px; font-size:24px; width:100%">
        <p style = "text-align:right">designed by Yasutaka Ikeda</p>
    </footer>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ritter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>